// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAtrL7Rcjqz3eAmjueBt_kffL7-DSwaohY',
    appId: '1:620131373785:web:afb8f56b47925465d824c8',
    messagingSenderId: '620131373785',
    projectId: 'overwatch-b52ab',
    authDomain: 'overwatch-b52ab.firebaseapp.com',
    storageBucket: 'overwatch-b52ab.appspot.com',
    measurementId: 'G-Y4NLXEYH43',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCJ5y6wwOQJdhFtjTmgsjM-OXgZhbJE4Eg',
    appId: '1:620131373785:android:d86d4db83d90b0f3d824c8',
    messagingSenderId: '620131373785',
    projectId: 'overwatch-b52ab',
    storageBucket: 'overwatch-b52ab.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDI3UT1UO2z48WsGtadDJqOZDIuift73FA',
    appId: '1:620131373785:ios:147c4cf407206707d824c8',
    messagingSenderId: '620131373785',
    projectId: 'overwatch-b52ab',
    storageBucket: 'overwatch-b52ab.appspot.com',
    iosBundleId: 'com.synzen.overwatch',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDI3UT1UO2z48WsGtadDJqOZDIuift73FA',
    appId: '1:620131373785:ios:147c4cf407206707d824c8',
    messagingSenderId: '620131373785',
    projectId: 'overwatch-b52ab',
    storageBucket: 'overwatch-b52ab.appspot.com',
    iosBundleId: 'com.synzen.overwatch',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAtrL7Rcjqz3eAmjueBt_kffL7-DSwaohY',
    appId: '1:620131373785:web:5ac88481fdb12383d824c8',
    messagingSenderId: '620131373785',
    projectId: 'overwatch-b52ab',
    authDomain: 'overwatch-b52ab.firebaseapp.com',
    storageBucket: 'overwatch-b52ab.appspot.com',
    measurementId: 'G-334M9HDHZY',
  );
}
